title: Aster Fu Portfolio
email: youtzor128@gmail.com
description: >-
  建築シミュレーション × 大気科学 × サステナブル建築設計｜学びと作品の記録
github_username: bananafu
minimal_mistakes_skin: aqua
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
markdown: kramdown
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Asia/Taipei

nav:
  - title: "Home"
    url: /
  - title: "About"
    url: "{{ '/about/' | relative_url }}"
  - title: "Portfolio"
    url: "{{ '/portfolio/' | relative_url }}"
  - title: "Contact"
    url: "{{ '/contact/' | relative_url }}"
  - title: "Skills"
    url: "{{ '/skills/' | relative_url }}"
  - title: "Projects"
    url: {{ '/projects/' | relative_url }}"
  - title: "Publications"
    url: {{ '/publications/' | relative_url }}"

include:
  - _pages
  
custom_css:
  - "/assets/css/custom.css"

header:
  overlay_color: "#000"
  overlay_filter: "0.3"
  show_overlay_excerpt: false
  actions:
    - label: "Learn More"
      url: "/about/"
    - label: "See My Projects"
      url: "/projects/"
